import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/common/header";

const mainFont = Rubik({
  variable: "--font-stack-sans",
  subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.variable} antialiased`}
      >
        <Header />
        <main className="h-full">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
